# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'File_Download.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(590, 200)
        Dialog.setMinimumSize(QtCore.QSize(400, 200))
        Dialog.setMaximumSize(QtCore.QSize(600, 200))
        self.textEdit_dir = QtWidgets.QTextEdit(Dialog)
        self.textEdit_dir.setGeometry(QtCore.QRect(50, 30, 361, 31))
        self.textEdit_dir.setObjectName("textEdit_dir")
        self.textEdit_url = QtWidgets.QTextEdit(Dialog)
        self.textEdit_url.setGeometry(QtCore.QRect(50, 80, 361, 31))
        self.textEdit_url.setObjectName("textEdit_url")
        self.textEdit_notice = QtWidgets.QTextEdit(Dialog)
        self.textEdit_notice.setGeometry(QtCore.QRect(250, 130, 161, 41))
        self.textEdit_notice.setObjectName("textEdit_notice")
        self.pushButton_download = QtWidgets.QPushButton(Dialog)
        self.pushButton_download.setGeometry(QtCore.QRect(100, 140, 81, 26))
        self.pushButton_download.setObjectName("pushButton_download")
        self.pushButton_cleanDir = QtWidgets.QPushButton(Dialog)
        self.pushButton_cleanDir.setGeometry(QtCore.QRect(460, 30, 81, 31))
        self.pushButton_cleanDir.setObjectName("pushButton_cleanDir")
        self.pushButton_cleanURL = QtWidgets.QPushButton(Dialog)
        self.pushButton_cleanURL.setGeometry(QtCore.QRect(460, 80, 81, 31))
        self.pushButton_cleanURL.setObjectName("pushButton_cleanURL")

        self.retranslateUi(Dialog)

        # 槽函数绑定
        self.pushButton_cleanDir.clicked.connect(Dialog.cleanDir)
        self.pushButton_cleanURL.clicked.connect(Dialog.cleanURL)
        self.pushButton_download.clicked.connect(Dialog.download)

        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_download.setText(_translate("Dialog", "下载"))
        self.pushButton_cleanDir.setText(_translate("Dialog", "清除目录"))
        self.pushButton_cleanURL.setText(_translate("Dialog", "清除URL"))
